spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: koala_back
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: ${JWT_ACCESS_TOKEN_MS}
  refresh-token-ms: ${JWT_REFRESH_TOKEN_MS}
