spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: koala_back
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 30
      max-lifetime: 240000
      leak-detection-threshold: 10000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: ${JWT_ACCESS_TOKEN_MS}
  refresh-token-ms: ${JWT_REFRESH_TOKEN_MS}

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}