version: '3'
services:
  backend:
    container_name: back-server
    build:
      context: ./backend/koala_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/koala_back/.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - koala

  frontend:
    container_name: front-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - koala

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - koala

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  koala:


